# Manipulação de Array com Numpy

In [1]:
import numpy as np

In [2]:
# OPERAÇÕES BÁSICAS COM VETORES

# criando vetores
u = np.array([1, 3])
v = np.array([3, 1])

In [ ]:
# Operações de subtracao e Soma com vetores
y = u - v
z = u + v

print(f"Vetor subtracao: {y}\nVetor soma: {z}")

Vetor sub: [-2  2]
Vetor soma: [4 4]


In [4]:
# Fazendo produto escalar e divisao de vetores
a = u / v
b = u * v   # multiplicacao de vetores

print(f"Vetor Divisao: {a}\nVetor Multiplicacao: {b}")

alpha = 2
escalar = alpha * u
print(f"\nProduto escalar de u por alpha: {escalar}")

Vetor Divisao: [0.33333333 3.        ]
Vetor Multiplicacao: [3 3]

Produto escalar de u por alpha: [2 6]


In [5]:
# Fazendo produto interno(escalar) e produto vetorial
interno = np.dot(u, v)

# Vetores tridimensionais
u3 = np.array([1, 3, 1])
v3 = np.array([3, 1, 1])

vetorial = np.cross(u3, v3)

print(f"Resultado produto interno: {interno}\nResultado Produto Vetorial: {vetorial}")

Resultado produto interno: 6
Resultado Produto Vetorial: [ 2  2 -8]


# Operações Básicas com Matrizes

In [7]:
# Criando matrizes
I = np.array([[1, 0], [0, 1]])    # Matriz identidade
A = np.array([[2, 1], [1, 2]])

In [14]:
B = A + I

print(f"Matriz A:\n {A}\n\nMatriz I:\n {I}\n\nMatriz B = A + I:\n {B}")

B = A - I

print(f"Matriz A:\n {A}\n\nMatriz I:\n {I}\n\nMatriz B = A - I:\n {B}")

Matriz A:
 [[2 1]
 [1 2]]

Matriz I:
 [[1 0]
 [0 1]]

Matriz B = A + I:
 [[3 1]
 [1 3]]
Matriz A:
 [[2 1]
 [1 2]]

Matriz I:
 [[1 0]
 [0 1]]

Matriz B = A - I:
 [[1 1]
 [1 1]]


In [16]:
# Realizando Multiplicação de Matrizes
M = np.matmul(A, I)

print(f"Matriz A:\n {A}\n\nMatriz I:\n {I}\n\nMatriz M = A x I:\n {M}")

Matriz A:
 [[2 1]
 [1 2]]

Matriz I:
 [[1 0]
 [0 1]]

Matriz M = A x I:
 [[2 1]
 [1 2]]
